CREATE TABLE [dbo].[TBFuncionario]
(
	[id_funcionario] INT NOT NULL IDENTITY(1,1), 
    [nome] VARCHAR(100) NOT NULL, 
    [cargo] VARCHAR(50) NOT NULL, 
    [ramal] VARCHAR(4) NOT NULL
	CONSTRAINT [PK_funcionario] PRIMARY KEY CLUSTERED

(
	[id_funcionario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
