CREATE TABLE [dbo].[TBSala]
(
	[id_sala] INT NOT NULL IDENTITY(1,1), 
    [nome_sala] VARCHAR(50) NOT NULL, 
    [numero_lugares] INT NOT NULL
	CONSTRAINT [PK_Sala] PRIMARY KEY CLUSTERED

(
	[id_sala] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
