CREATE TABLE [dbo].[TBLoan]
(
	[IdLoan] INT NOT NULL IDENTITY, 
    [NameClient] VARCHAR(100) NULL, 
    [DateDevolution] DATE NULL, 
    [BookId] INT NULL,
	CONSTRAINT [FK_TBLoan_ToTBBook] FOREIGN KEY ([BookId]) REFERENCES [TBBook]([IdBook]),
	CONSTRAINT [PK_Loan] PRIMARY KEY CLUSTERED
(
	[IdLoan] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
