CREATE TABLE [dbo].[TBProduct]
(
	[IdProduct] INT NOT NULL IDENTITY(1,1), 
    [Name] VARCHAR(100) NOT NULL, 
    [CostPrice] DECIMAL(18, 2) NOT NULL, 
    [SalePrice] DECIMAL(18, 2) NOT NULL, 
    [Fabrication] DATE NOT NULL, 
    [Expiration] DATE NOT NULL, 
    [IsAvaliable] BIT NOT NULL,
	CONSTRAINT [PK_Products] PRIMARY KEY CLUSTERED

(
	[IdProduct] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
